# Generated by Django 5.1.4 on 2024-12-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="password",
        ),
        migrations.RemoveField(
            model_name="member",
            name="username",
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
