# Generated by Django 5.1.4 on 2024-12-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0002_remove_member_password_remove_member_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="member",
            managers=[],
        ),
    ]
