# Generated by Django 5.1.4 on 2024-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0003_alter_member_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(
                default="default_password", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
