# Generated by Django 5.1.4 on 2024-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0004_member_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(default="default_password", max_length=128),
        ),
    ]
