# Generated by Django 5.1.4 on 2024-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0005_alter_member_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="descrip",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
