# Generated by Django 5.1.4 on 2024-12-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0006_position_descrip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="position",
            old_name="descrip",
            new_name="descript",
        ),
    ]
