# Generated by Django 5.1.4 on 2024-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0007_rename_descrip_position_descript"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="thumbnail",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="thumbnail/%Y/"
            ),
        ),
    ]
